### PR TITLE
Use mapping service

### LINKED ISSUE #26: Add helper entity to DTO mapper methods
It will be very useful and convenient to have mapper methods that automatically map entities to DTOs which will be returned to the client. 
One example is [here ](https://github.com/ofuochi/node-typescript-boilerplate/blob/4a83d236a0b4a9952d2a5d72e3a5992f4d45df03/src/ui/api/controllers/tenant_controller.ts#L39). 
```js
const tenants = await this._tenantRepository.findManyByQuery({ name: tenantName });
const tenantDtoList = tenants.map(t => {
   let tenantDto: TenantDto = {
        name: t.name,
        description: t.description,
        isActive: t.isActive,
        id: t.id
    };
    return tenantDto;
});

return tenantDtoList
```
This can quickly get messy if the DTO has many properties that need to be manually mapped to it. It will be helpful to have an auto mapper method or package that can do this.

### PR DESCRIPTION
**Pull request by artfuldev**
Fixes #26

### CODE REVIEW

**Comment by artfuldev** [comment]
Sorry, will merge the changes now.

**Comment by artfuldev** [comment]
My formatting is sometimes not in line with what you have setup - is there some tool/extension I need? I use VS Code for editing with editorconfig extension, but I'm missing something else.

**Comment by ofuochi** [comment]
@artfuldev I use vscode too. One of the issues is for linting (eslint). I'll push the linting fix and then you can make another PR

**Comment by ofuochi** [comment]
@artfuldev you may update this PR now.

**Comment by artfuldev** [comment]
@ofuochi I think named exports are a better idea than default exports because they enforce consistent naming while importing.

**Comment by ofuochi** [comment]
@artfuldev you are absolutely right. I'll add that as an issue and if you have time you may take it on.

**Comment by artfuldev** [comment]
@ofuochi also consider 2-space indents 😄

**Comment by ofuochi** [comment]
@artfuldev 😄

**Pull request merged**
